[package]
name = "mufbot-dc"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
dotenv = "0.15.0"
poise = "0.6.1"
sqlite = "0.36.1"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
