# .github/workflows/release.yml

on:
    release:
      types: [created]

permissions: write-all

jobs:
    release:
      name: release ${{ matrix.target }}
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
      steps:
        - uses: actions/checkout@master
        - name: Install latest rust toolchain
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            default: true
            override: true
        - name: Build
          run: cargo build --all --release && strip target/release/mufbot-dc
        - name: Release
          uses: softprops/action-gh-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            files: target/release/mufbot-dc